### ISSUE TITLE
Add Text Alignment

### ISSUE THREAD

**Issue by AndreyNazarchuk** [androidessence/RichTextView#8]
Hello,

Can this library align some text left, some center, and some left?

Thanks!

**Comment by AdamMc331** [comment]
Great idea! I will look into that and report back by the end of the week if I can make it work.

**Comment by AdamMc331** [comment]
But to answer your question: no, not in the current version haha

**Comment by AndreyNazarchuk** [comment]
Okay, thanks so much, right now I am using a mix of views with transparent
backgrounds.

**Comment by AdamMc331** [comment]
So far, I've found out this is possible, but I think it's only possible when there are new line breaks between the pieces of text. Do you think that would work for you, or not really?

If you need it in one line, I think you may as well end up using multiple TextViews, if I'm honest.

<img src='http://i.imgur.com/2hDEy2n.png' width='400' height='640' />

**Comment by AndreyNazarchuk** [comment]
That's how I do it right now, except separate views, then I make them
transparent and move them up.

**Comment by AdamMc331** [comment]
Closing this since it's not possible to do on the same line.
