### ISSUE TITLE
Any idea of how to add a Bullet List and a Number List?

### ISSUE THREAD

**Issue by raghunandankavi2010** [androidessence/RichTextView#9]
This is actually request for enhancement. Can we have a bullet list and a Number List as well.

Here's a library that does that. https://github.com/1gravity/Android-RTEditor.  They have a LeadingMarginSpan and draw numbers and bullet.

**Comment by AdamMc331** [comment]
I'll take a look to see if I can add a list span. Thanks for the suggestion!

**Comment by AdamMc331** [comment]
Numbered list has been added, thank you Raghunandan! Bulleted list is still a possibility to look into.

**Comment by raghunandankavi2010** [comment]
Sure. will look into it tomorrow. Will see if we can add some more spans also.
